nelmio_api_doc:
    documentation:
        info:
            title: Hexagonal Blog
            description: IPGlobal Test
            version: 0.0.1
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!(/doc|/doc.json)$) # Accepts routes under /api except /api/doc
