version: '3.8'

services:
  phpfpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - phpfpm

volumes:
  db_data:
