controllersapi:
    resource:
        path: ../src/Back
        namespace: App\Back
    type: attribute
    prefix: '/api'

controllersfront:
    resource:
        path: ../src/Front
        namespace: App\Front
    type: attribute

