controllersapi:
    resource:
        path: ../src/Api
        namespace: App\Api
    type: attribute
    prefix: '/api'

controllersfront:
    resource:
        path: ../src/Front
        namespace: App\Front
    type: attribute

